#!/usr/bin/env python3
"""rebuild_doc_indices.py — regenerate docs/{ideas,experiments,findings}/README.md from frontmatter.

Usage:
    python3 scripts/rebuild_doc_indices.py
    # dry-run:
    python3 scripts/rebuild_doc_indices.py --check
"""
import argparse
import glob
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).parent.parent


def parse_frontmatter(path: Path):
    try:
        text = path.read_text()
    except (OSError, UnicodeDecodeError):
        return None
    m = re.match(r"^---\n(.*?)\n---\n", text, flags=re.S)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        print(f"WARN: {path} has malformed frontmatter: {e}", file=sys.stderr)
        return None


def rebuild_ideas(write: bool):
    dir_ = REPO_ROOT / "docs" / "ideas"
    ideas = []
    for p in sorted(dir_.glob("IDEA_*.md")):
        if p.name.endswith("TEMPLATE.md"):
            continue
        fm = parse_frontmatter(p)
        if fm and "id" in fm:
            ideas.append((fm, p))

    active_statuses = {"draft", "audited", "approved", "in-experiment"}
    archive_statuses = {"validated", "killed", "superseded"}

    def expected_bpb_center(fm):
        rng = fm.get("expected_bpb", [0, 0])
        if isinstance(rng, list) and len(rng) == 2:
            return (rng[0] + rng[1]) / 2
        return 0

    active = [i for i in ideas if (i[0].get("status") or "").strip() in active_statuses]
    archive = [i for i in ideas if (i[0].get("status") or "").strip() in archive_statuses]
    # Sort active: by status (order active_statuses), then by most-negative expected center
    status_order = {"in-experiment": 0, "approved": 1, "audited": 2, "draft": 3}
    active.sort(key=lambda x: (status_order.get(x[0].get("status"), 9), expected_bpb_center(x[0])))
    archive.sort(key=lambda x: x[0].get("updated", ""), reverse=True)

    lines = ["# docs/ideas/ — design-stage candidate inventory\n"]
    lines.append("\nGenerated by `scripts/rebuild_doc_indices.py`. Don't hand-edit the tables below.\n")
    lines.append("\n**How to add an idea**: copy `TEMPLATE.md` to `IDEA_<next_id>_<slug>.md`, fill frontmatter + content, rerun this script.\n")
    lines.append("\n## Active ideas\n")
    lines.append("\n| ID | Slug | Layer | Status | Expected BPB | Next step |\n|---|---|---|---|---|---|\n")
    for fm, p in active:
        rng = fm.get("expected_bpb", [0, 0])
        rng_str = f"[{rng[0]}, {rng[1]}]" if isinstance(rng, list) and len(rng) == 2 else str(rng)
        lines.append(f"| {fm['id']} | [{fm.get('slug','')}]({p.name}) | {fm.get('layer','')} | {fm.get('status','')} | {rng_str} | {fm.get('next_step', '')} |\n")
    if not active:
        lines.append("| _(none yet)_ | | | | | |\n")

    lines.append("\n## Killed / superseded / validated (archive)\n")
    lines.append("\n| ID | Slug | Layer | Status | Why / outcome |\n|---|---|---|---|---|\n")
    for fm, p in archive:
        lines.append(f"| {fm['id']} | [{fm.get('slug','')}]({p.name}) | {fm.get('layer','')} | {fm.get('status','')} | {fm.get('archive_note', '')} |\n")
    if not archive:
        lines.append("| _(none yet)_ | | | | |\n")

    lines.append("\n## Lifecycle\n")
    lines.append("""
```
draft ──audited──▶ audited ──falsifiable──▶ approved ──schedule──▶ in-experiment
                                                                        │
                                                                        ├──▶ validated (finding published)
                                                                        ├──▶ killed (falsification met)
                                                                        └──▶ superseded (replaced by a newer idea)
```

""")
    lines.append("## Related\n\n")
    lines.append("- `docs/research/RESEARCH_PROTOCOL.md` — how these 1-pagers get created\n")
    lines.append("- `docs/research/DOC_SYSTEM.md` — full doc architecture\n")
    lines.append("- `docs/research/STACK_NOVELTY_TRACKER_v2.md` — canonical catalog\n")
    lines.append("- `docs/research/MOONSHOT_RULES.md` — legality gate\n")
    lines.append("- `docs/experiments/` — runs that test these ideas\n")
    lines.append("- `docs/findings/` — paper-format results\n")

    write_output(dir_ / "README.md", "".join(lines), write)


def rebuild_experiments(write: bool):
    dir_ = REPO_ROOT / "docs" / "experiments"
    exps = []
    for p in sorted(dir_.glob("EXP_*.md")):
        if p.name.endswith("TEMPLATE.md"):
            continue
        fm = parse_frontmatter(p)
        if fm and "id" in fm:
            exps.append((fm, p))
    exps.sort(key=lambda x: x[0].get("started", ""), reverse=True)

    running = [e for e in exps if (e[0].get("status") or "").strip() == "running"]
    complete = [e for e in exps if (e[0].get("status") or "").strip() == "complete"]
    other = [e for e in exps if (e[0].get("status") or "").strip() not in ("running", "complete")]

    def config_summary(fm):
        cfg = fm.get("config") or {}
        if not isinstance(cfg, dict):
            return ""
        return ", ".join(f"{k}={v}" for k, v in list(cfg.items())[:4])

    lines = ["# docs/experiments/ — experiment run log\n"]
    lines.append("\nGenerated by `scripts/rebuild_doc_indices.py`. Don't hand-edit the tables below.\n")
    lines.append("\n## Recent (all statuses)\n")
    lines.append("\n| ID | Started | Idea | Config | Status | val_bpb |\n|---|---|---|---|---|---:|\n")
    for fm, p in exps[:30]:
        val_bpb = fm.get("val_bpb", "")
        lines.append(f"| [{fm['id']}]({p.name}) | {fm.get('started','')} | [{fm.get('idea','')}](../ideas/{fm.get('idea','')}_*.md) | {config_summary(fm)} | {fm.get('status','')} | {val_bpb} |\n")
    if not exps:
        lines.append("| _(none yet)_ | | | | | |\n")

    lines.append("\n## Running now\n")
    lines.append("\n| ID | Started | Pod | Idea |\n|---|---|---|---|\n")
    for fm, p in running:
        lines.append(f"| [{fm['id']}]({p.name}) | {fm.get('started','')} | {fm.get('pod','')} | {fm.get('idea','')} |\n")
    if not running:
        lines.append("| _(none)_ | | | |\n")

    lines.append("\n## Complete\n")
    lines.append("\n| ID | Date | Idea | Outcome | val_bpb |\n|---|---|---|---|---:|\n")
    for fm, p in complete:
        val_bpb = fm.get("val_bpb", "")
        lines.append(f"| [{fm['id']}]({p.name}) | {fm.get('started','')[:10]} | {fm.get('idea','')} | {fm.get('outcome', '')} | {val_bpb} |\n")
    if not complete:
        lines.append("| _(none)_ | | | | |\n")

    lines.append("\n## Related\n\n")
    lines.append("- `docs/ideas/` — parent ideas\n")
    lines.append("- `docs/findings/` — papers produced\n")
    lines.append("- `docs/research/RESEARCH_LOG.md` — chronological event log\n")
    lines.append("- `POD_HOSTS.env` — pod endpoints\n")
    lines.append("- `scripts/pod_run_h100.sh` — command dispatcher\n")

    write_output(dir_ / "README.md", "".join(lines), write)


def rebuild_findings(write: bool):
    dir_ = REPO_ROOT / "docs" / "findings"
    findings = []
    for p in sorted(dir_.glob("FINDING_*.md")):
        if p.name.endswith("TEMPLATE.md"):
            continue
        fm = parse_frontmatter(p)
        if fm:
            findings.append((fm, p))
    findings.sort(key=lambda x: x[0].get("date", ""), reverse=True)

    lines = ["# docs/findings/ — paper-format results\n"]
    lines.append("\nGenerated by `scripts/rebuild_doc_indices.py`. Don't hand-edit the table below.\n")
    lines.append("\n## Findings\n")
    lines.append("\n| Date | Title | Ideas | Headline metric | Updates |\n|---|---|---|---|---|\n")
    for fm, p in findings:
        updates = fm.get("updates") or []
        updates_str = ", ".join(updates) if isinstance(updates, list) else str(updates)
        ideas_str = ", ".join(fm.get("ideas") or [])
        lines.append(f"| {fm.get('date','')} | [{fm.get('title','')}]({p.name}) | {ideas_str} | {fm.get('headline_metric','')} | {updates_str} |\n")
    if not findings:
        lines.append("| _(none yet)_ | | | | |\n")

    lines.append("\n## Legacy mini-papers (pre-doc-system)\n\n")
    lines.append("- `docs/minipapers/MINIPAPER_TABULATION_HASH.md`\n")
    lines.append("- `docs/research/STACK_UTILISATION_RESULTS.md`\n")
    lines.append("- `docs/research/FLOOR_RESULTS.md`\n")
    lines.append("- `docs/research/MOONSHOT_RULES.md`\n")
    lines.append("\nFuture mini-papers go here as new FINDING docs.\n")
    lines.append("\n## Paper style (reminder from memory)\n\n")
    lines.append("1. TL;DR (1–3 sentences)\n2. Background\n3. Method\n4. Results (tables + ASCII diagram)\n5. Discussion / implications\n6. Simple worked example\n7. Limitations / follow-ups\n")

    write_output(dir_ / "README.md", "".join(lines), write)


def write_output(path: Path, content: str, write: bool):
    if not write:
        # dry-run: compare
        if path.exists() and path.read_text() == content:
            print(f"  ✓ {path.relative_to(REPO_ROOT)} up-to-date")
        else:
            print(f"  × {path.relative_to(REPO_ROOT)} WOULD CHANGE")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  ✓ wrote {path.relative_to(REPO_ROOT)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="Dry-run; compare generated content vs existing README")
    args = ap.parse_args()
    write = not args.check
    rebuild_ideas(write)
    rebuild_experiments(write)
    rebuild_findings(write)

if __name__ == "__main__":
    main()
